### ISSUE TITLE
link prompt not appearing

### ISSUE THREAD

**Issue by alexHunter854** [richiksc/atom-live-server-plus#14]
If you have a problem launching a live-server, please try the following steps:

1. Make sure you use the right hotkeys. After v2.0.0, the keys became `ctrl-alt` combination.✔
2. Try launching live-server from the top menu: `Package -> live-server -> Start Server` to see if it works.✔

when I start up the live server, both with the dropdown menu and without, the green prompt at the top of the screen that says "live server started (link)" doesn't show up.

this doesn't seem like a major problem but it is supremely annoying, I couldn't tell you the steps to reproduce but the only thing I can say is that it worked before I added node.js to my project

**Comment by richiksc** [comment]
@alexHunter854 Thanks for the report. I no longer use Atom or actively develop this extension, so I may not be able to fix this. By any chance, did you create an `.atom-live-server.json` file before it stopped working?

**Comment by alexHunter854** [comment]
I figured out what it was, I tried to install console2 beforehand and messed with the comSpec environment variable, changing it back to C:/Windows/System32/com.exe worked fine
