### ISSUE TITLE
# Errorserver is not defined 

### ISSUE THREAD

**Issue by MSUIK** [richiksc/atom-live-server-plus#4]
If you have a problem launching a live-server, please try following steps:

1. Make sure you use the right hotkeys. After v2.0.0, the keys became `ctrl-alt` combination.
2. Try launching live-server from top menu: `Package -> live-server -> Start Server` to see if it works.

**Comment by richiksc** [comment]
What is your issue?

**Comment by MSUIK** [comment]
Thanks for your good response .but  i have fixed  my error  now.

**Comment by richiksc** [comment]
Ok, thanks for commenting. I'm glad you were able to resolve your issue. Closing.
